### ISSUE TITLE
Remove ISSUE_TEMPLATE.md

### ISSUE THREAD

**Issue by sboerrigter** [trendwerk/bedrock#13]
I think we should remove ISSUE_TEMPLATE.md from our fork so we can report issues faster. Right now we have to delete the default comment on every new issue.

<img width="1007" alt="screen shot 2017-01-25 at 15 49 55" src="https://cloud.githubusercontent.com/assets/786875/22295156/352b672e-e316-11e6-897f-b4a4627d078d.png">

**Comment by haroldangenent** [comment]
Shouldn't be a problem if you install using `composer create-project`. Closing this as invalid.
